name: Go CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: backend/go.mod
    - name: Format Check
      run: gofmt -d $(git ls-files '*.go') | tee fmt.diff && test ! -s fmt.diff
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test ./...
