name: Go

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: gofmt
        run: |
          out=$(gofmt -l *.go)
          if [ -n "$out" ]; then
            echo "$out"
            exit 1
          fi
      - name: go vet
        run: go vet ./...
      - name: go test
        run: go test ./...
