name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Check formatting
        run: |
          files=$(gofmt -l $(find . -name '*.go' -not -path './vendor/*'))
          if [ -n "$files" ]; then
            echo "The following files need gofmt:" >&2
            echo "$files" >&2
            exit 1
          fi
      - name: Run tests
        run: |
          cd backend
          go test ./...
